services:
  web:
    image: arlindoas2/simulador-do-caos:v2
    ports:
      - 8080:3000
    restart: always
    healthcheck: 
      disable: true 
    cpuset: "0"
    memswap_limit: 512M
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M